/**
 * AUTO-GENERATED FILE — do not edit by hand.
 *
 * TypeScript types for DuckDB's serialization schemas, generated by
 * `scripts/generate-serialization-types.ts`. Regenerate with:
 *
 *     bun run scripts/generate-serialization-types.ts
 */

/** Types defined outside these schemas; refine as needed. */
export type DuckDBValue = unknown;
export type DuckDBLogicalType = unknown;

export interface AddColumnInfo extends AlterTableInfo {
  new_column: ColumnDefinition;
  if_column_not_exists: boolean;
  alter_table_type: "ADD_COLUMN";
}
export interface AddConstraintInfo extends AlterTableInfo {
  constraint: AnyConstraint | null;
  alter_table_type: "ADD_CONSTRAINT";
}
export interface AddFieldInfo extends AlterTableInfo {
  new_field: ColumnDefinition;
  if_field_not_exists: boolean;
  column_path: string[];
  alter_table_type: "ADD_FIELD";
}
export interface AggregateStateTypeInfo extends ExtraTypeInfo {
  function_name: string;
  return_type: DuckDBLogicalType;
  bound_argument_types: DuckDBLogicalType[];
  type: "AGGREGATE_STATE_TYPE_INFO";
}
export interface AlterDatabaseInfo extends AlterInfo {
  alter_database_type: string;
  type: "ALTER_DATABASE";
}
export interface AlterForeignKeyInfo extends AlterTableInfo {
  fk_table: string;
  pk_columns: string[];
  fk_columns: string[];
  pk_keys: number[];
  fk_keys: number[];
  alter_fk_type: string;
  alter_table_type: "FOREIGN_KEY_CONSTRAINT";
}
export interface AlterInfo extends ParseInfo {
  type: string;
  catalog: string;
  schema: string;
  name: string;
  if_not_found: string;
  allow_internal: boolean;
  info_type: "ALTER_INFO";
}
export interface AlterTableInfo extends AlterInfo {
  alter_table_type: string;
  type: "ALTER_TABLE";
}
export interface AlterViewInfo extends AlterInfo {
  alter_view_type: string;
  type: "ALTER_VIEW";
}
export interface AnyTypeInfo extends ExtraTypeInfo {
  target_type: DuckDBLogicalType;
  cast_score: number;
  type: "ANY_TYPE_INFO";
}
export interface ArrayTypeInfo extends ExtraTypeInfo {
  child_type: DuckDBLogicalType;
  size: number;
  type: "ARRAY_TYPE_INFO";
}
export interface AtClause {
  unit: string;
  expr: AnyParsedExpression | null;
}
export interface AttachInfo extends ParseInfo {
  name: string;
  path: string;
  options: Record<string, DuckDBValue>;
  on_conflict: string;
  info_type: "ATTACH_INFO";
}
export interface BaseReservoirSampling {
  next_index_to_sample: number;
  min_weight_threshold: number;
  min_weighted_entry_index: number;
  num_entries_to_skip_b4_next_sample: number;
  num_entries_seen_total: number;
  reservoir_weights: [number, number][];
}
export interface BaseTableRef extends TableRef {
  schema_name: string;
  table_name: string;
  column_name_alias: string[];
  catalog_name: string;
  at_clause: AtClause | null;
  type: "BASE_TABLE";
}
export interface BetweenExpression extends ParsedExpression {
  input: AnyParsedExpression | null;
  lower: AnyParsedExpression | null;
  upper: AnyParsedExpression | null;
  class: "BETWEEN";
}
export interface BlockPointer {
  block_id: number;
  offset: number;
}
export interface BlockingSample {
  base_reservoir_sample: BaseReservoirSampling | null;
  type: string;
  destroyed: boolean;
}
export interface BoundAggregateExpression extends Expression {
  expression_class: "BOUND_AGGREGATE";
}
export interface BoundBetweenExpression extends Expression {
  input: AnyExpression | null;
  lower: AnyExpression | null;
  upper: AnyExpression | null;
  lower_inclusive: boolean;
  upper_inclusive: boolean;
  expression_class: "BOUND_BETWEEN";
}
export interface BoundCaseCheck {
  when_expr: AnyExpression | null;
  then_expr: AnyExpression | null;
}
export interface BoundCaseExpression extends Expression {
  return_type: DuckDBLogicalType;
  case_checks: BoundCaseCheck[];
  else_expr: AnyExpression | null;
  expression_class: "BOUND_CASE";
}
export interface BoundCastExpression extends Expression {
  child: AnyExpression | null;
  return_type: DuckDBLogicalType;
  try_cast: boolean;
  expression_class: "BOUND_CAST";
}
export interface BoundColumnRefExpression extends Expression {
  return_type: DuckDBLogicalType;
  binding: ColumnBinding;
  depth: number;
  expression_class: "BOUND_COLUMN_REF";
}
export interface BoundComparisonExpression extends Expression {
  left: AnyExpression | null;
  right: AnyExpression | null;
  expression_class: "BOUND_COMPARISON";
}
export interface BoundConjunctionExpression extends Expression {
  children: AnyExpression[];
  expression_class: "BOUND_CONJUNCTION";
}
export interface BoundConstantExpression extends Expression {
  value: DuckDBValue;
  expression_class: "BOUND_CONSTANT";
}
export interface BoundDefaultExpression extends Expression {
  return_type: DuckDBLogicalType;
  expression_class: "BOUND_DEFAULT";
}
export interface BoundExportData extends ParseInfo {
  data: ExportedTableInfo[];
  info_type: "BOUND_EXPORT_DATA";
}
export interface BoundFunctionExpression extends Expression {
  expression_class: "BOUND_FUNCTION";
}
export interface BoundLambdaExpression extends Expression {
  return_type: DuckDBLogicalType;
  lambda_expr: AnyExpression | null;
  captures: AnyExpression[];
  parameter_count: number;
  expression_class: "BOUND_LAMBDA";
}
export interface BoundLambdaRefExpression extends Expression {
  return_type: DuckDBLogicalType;
  binding: ColumnBinding;
  lambda_index: number;
  depth: number;
  expression_class: "BOUND_LAMBDA_REF";
}
export interface BoundLimitNode {
  type: string;
  constant_integer: number;
  constant_percentage: number;
  expression: AnyExpression | null;
}
export interface BoundMergeIntoAction {
  action_type: string;
  condition: AnyExpression | null;
  columns: number[];
  expressions: AnyExpression[];
  column_index_map: Array<[number, number]>;
  update_is_del_and_insert: boolean;
}
export interface BoundOperatorExpression extends Expression {
  return_type: DuckDBLogicalType;
  children: AnyExpression[];
  expression_class: "BOUND_OPERATOR";
}
export interface BoundOrderByNode {
  type: string;
  null_order: string;
  expression: AnyExpression | null;
}
export interface BoundOrderModifier {
  orders: BoundOrderByNode[];
}
export interface BoundParameterData {
  value: DuckDBValue;
  return_type: DuckDBLogicalType;
}
export interface BoundParameterExpression extends Expression {
  identifier: string;
  return_type: DuckDBLogicalType;
  parameter_data: BoundParameterData | null;
  expression_class: "BOUND_PARAMETER";
}
export interface BoundPivotInfo {
  group_count: number;
  types: DuckDBLogicalType[];
  pivot_values: string[];
  aggregates: AnyExpression[];
}
export interface BoundReferenceExpression extends Expression {
  return_type: DuckDBLogicalType;
  index: number;
  expression_class: "BOUND_REF";
}
export interface BoundUnnestExpression extends Expression {
  return_type: DuckDBLogicalType;
  child: AnyExpression | null;
  expression_class: "BOUND_UNNEST";
}
export interface BoundWindowExpression extends Expression {
  expression_class: "BOUND_WINDOW";
}
export interface CSVOption<T> {
  set_by_user: boolean;
  value: T;
}
export interface CTENode extends QueryNode {
  cte_name: string;
  query: AnyQueryNode | null;
  child: AnyQueryNode | null;
  aliases: string[];
  materialized: string;
  type: "CTE_NODE";
}
export interface CaseCheck {
  when_expr: AnyParsedExpression | null;
  then_expr: AnyParsedExpression | null;
}
export interface CaseExpression extends ParsedExpression {
  case_checks: CaseCheck[];
  else_expr: AnyParsedExpression | null;
  class: "CASE";
}
export interface CastExpression extends ParsedExpression {
  child: AnyParsedExpression | null;
  cast_type: DuckDBLogicalType;
  try_cast: boolean;
  class: "CAST";
}
export interface CatalogEntryInfo {
  type: string;
  schema: string;
  name: string;
}
export interface ChangeColumnTypeInfo extends AlterTableInfo {
  column_name: string;
  target_type: DuckDBLogicalType;
  expression: AnyParsedExpression | null;
  alter_table_type: "ALTER_COLUMN_TYPE";
}
export interface ChangeOwnershipInfo extends AlterInfo {
  entry_catalog_type: string;
  owner_schema: string;
  owner_name: string;
  type: "CHANGE_OWNERSHIP";
}
export interface CheckConstraint extends Constraint {
  expression: AnyParsedExpression | null;
  type: "CHECK";
}
export interface CollateExpression extends ParsedExpression {
  child: AnyParsedExpression | null;
  collation: string;
  class: "COLLATE";
}
export interface ColumnBinding {
  table_index: number;
  column_index: number;
}
export interface ColumnDataRef extends TableRef {
  expected_names: string[];
  collection: unknown | null;
  type: "COLUMN_DATA";
}
export interface ColumnDefinition {
  name: string;
  type: DuckDBLogicalType;
  expression: AnyParsedExpression | null;
  category: string;
  compression_type: string;
  comment: DuckDBValue;
  tags: Record<string, string>;
}
export interface ColumnIndex {
  index: number;
  child_indexes: ColumnIndex[];
  index_type: string;
  type: DuckDBLogicalType;
  field: string;
  has_index: boolean;
}
export interface ColumnInfo {
  names: string[];
  types: DuckDBLogicalType[];
}
export interface ColumnList {
  columns: ColumnDefinition[];
}
export interface ColumnRefExpression extends ParsedExpression {
  column_names: string[];
  class: "COLUMN_REF";
}
export interface CommonTableExpressionInfo {
  aliases: string[];
  query: SelectStatement | null;
  materialized: string;
  key_targets: AnyParsedExpression[];
}
export interface CommonTableExpressionMap {
  map: Record<string, CommonTableExpressionInfo>;
}
export interface ComparisonExpression extends ParsedExpression {
  left: AnyParsedExpression | null;
  right: AnyParsedExpression | null;
  class: "COMPARISON";
}
export interface ConjunctionAndFilter extends TableFilter {
  child_filters: AnyTableFilter[];
  filter_type: "CONJUNCTION_AND";
}
export interface ConjunctionExpression extends ParsedExpression {
  children: AnyParsedExpression[];
  class: "CONJUNCTION";
}
export interface ConjunctionOrFilter extends TableFilter {
  child_filters: AnyTableFilter[];
  filter_type: "CONJUNCTION_OR";
}
export interface ConstantExpression extends ParsedExpression {
  value: DuckDBValue;
  class: "CONSTANT";
}
export interface ConstantFilter extends TableFilter {
  comparison_type: string;
  constant: DuckDBValue;
  filter_type: "CONSTANT_COMPARISON";
}
export interface Constraint {
  type: string;
}
export interface CopyDatabaseInfo extends ParseInfo {
  target_database: string;
  entries: AnyCreateInfo[];
  info_type: "COPY_DATABASE_INFO";
}
export interface CopyInfo extends ParseInfo {
  catalog: string;
  schema: string;
  table: string;
  select_list: string[];
  is_from: boolean;
  format: string;
  file_path: string;
  options: Record<string, DuckDBValue[]>;
  select_statement: AnyQueryNode | null;
  is_format_auto_detected: boolean;
  info_type: "COPY_INFO";
}
export interface CreateIndexInfo extends CreateInfo {
  name: string;
  table: string;
  constraint_type: string;
  parsed_expressions: AnyParsedExpression[];
  scan_types: DuckDBLogicalType[];
  names: string[];
  column_ids: number[];
  options: Record<string, DuckDBValue>;
  index_type_name: string;
  type: "INDEX_ENTRY";
}
export interface CreateInfo {
  type: string;
  catalog: string;
  schema: string;
  temporary: boolean;
  internal: boolean;
  on_conflict: string;
  sql: string;
  comment: DuckDBValue;
  tags: Record<string, string>;
  /** @since v0.10.3 */
  dependencies: LogicalDependencyList;
}
export interface CreateMacroInfo extends CreateInfo {
  name: string;
  function: AnyMacroFunction | null;
  extra_functions: AnyMacroFunction[];
  type: "MACRO_ENTRY" | "TABLE_MACRO_ENTRY";
}
export interface CreateSchemaInfo extends CreateInfo {
  type: "SCHEMA_ENTRY";
}
export interface CreateSequenceInfo extends CreateInfo {
  name: string;
  usage_count: number;
  increment: number;
  min_value: number;
  max_value: number;
  start_value: number;
  cycle: boolean;
  type: "SEQUENCE_ENTRY";
}
export interface CreateTableInfo extends CreateInfo {
  table: string;
  columns: ColumnList;
  constraints: AnyConstraint[];
  query: SelectStatement | null;
  partition_keys: AnyParsedExpression[];
  sort_keys: AnyParsedExpression[];
  options: Record<string, AnyParsedExpression>;
  type: "TABLE_ENTRY";
}
export interface CreateTypeInfo extends CreateInfo {
  name: string;
  logical_type: DuckDBLogicalType;
  type: "TYPE_ENTRY";
}
export interface CreateViewInfo extends CreateInfo {
  view_name: string;
  aliases: string[];
  types: DuckDBLogicalType[];
  query: SelectStatement | null;
  names: string[];
  /** @since v1.5.0 */
  column_comments: DuckDBValue[];
  /** @since v1.5.0 */
  column_comments_map: Record<string, DuckDBValue>;
  type: "VIEW_ENTRY";
}
export interface DataPointer {
  tuple_count: number;
  block_pointer: BlockPointer;
  compression_type: string;
  statistics: unknown;
  segment_state: unknown | null;
}
export interface DecimalTypeInfo extends ExtraTypeInfo {
  width: number;
  scale: number;
  type: "DECIMAL_TYPE_INFO";
}
export interface DefaultExpression extends ParsedExpression {
  class: "DEFAULT";
}
export interface DetachInfo extends ParseInfo {
  name: string;
  if_not_found: string;
  info_type: "DETACH_INFO";
}
export interface DistinctModifier extends ResultModifier {
  distinct_on_targets: AnyParsedExpression[];
  type: "DISTINCT_MODIFIER";
}
export interface DistinctStatistics {
  sample_count: number;
  total_count: number;
  log: unknown | null;
}
export interface DropInfo extends ParseInfo {
  type: string;
  catalog: string;
  schema: string;
  name: string;
  if_not_found: string;
  cascade: boolean;
  allow_drop_internal: boolean;
  extra_drop_info: AnyExtraDropInfo | null;
  info_type: "DROP_INFO";
}
export interface DropNotNullInfo extends AlterTableInfo {
  column_name: string;
  alter_table_type: "DROP_NOT_NULL";
}
export interface DynamicFilter extends TableFilter {
  filter_type: "DYNAMIC_FILTER";
}
export interface EmptyTableRef extends TableRef {
  type: "EMPTY_FROM";
}
export interface EnumTypeInfo extends ExtraTypeInfo {
  type: "ENUM_TYPE_INFO";
}
export interface ExportedTableData {
  table_name: string;
  schema_name: string;
  database_name: string;
  file_path: string;
  not_null_columns: string[];
}
export interface ExportedTableInfo {
  table_data: ExportedTableData;
}
export interface Expression {
  expression_class: string;
  type: string;
  alias: string;
  query_location: number;
}
export interface ExpressionFilter extends TableFilter {
  expr: AnyExpression | null;
  filter_type: "EXPRESSION_FILTER";
}
export interface ExpressionListRef extends TableRef {
  expected_names: string[];
  expected_types: DuckDBLogicalType[];
  values: AnyParsedExpression[][];
  type: "EXPRESSION_LIST";
}
export interface ExtensionInstallInfo {
  mode: string;
  full_path: string;
  repository_url: string;
  version: string;
  etag: string;
}
export interface ExtensionTypeInfo {
  modifiers: LogicalTypeModifier[];
  properties: Record<string, DuckDBValue>;
}
export interface ExtraDropInfo {
  info_type: string;
}
export interface ExtraDropSecretInfo extends ExtraDropInfo {
  persist_mode: string;
  secret_storage: string;
  info_type: "SECRET_INFO";
}
export interface ExtraOperatorInfo {
  file_filters: string;
  total_files: number;
  filtered_files: number;
  sample_options: SampleOptions | null;
}
export interface ExtraTypeInfo {
  type: string;
  alias: string;
  extension_info: ExtensionTypeInfo | null;
}
export interface FileNameSegment {
  type: string;
  data: string;
}
export interface FilenamePattern {
  base: string;
  pos: number;
  uuid: boolean;
  segments: FileNameSegment[];
}
export interface FixedSizeAllocatorInfo {
  segment_size: number;
  buffer_ids: number[];
  block_pointers: BlockPointer[];
  segment_counts: number[];
  allocation_sizes: number[];
  buffers_with_free_space: number[];
}
export interface ForeignKeyConstraint extends Constraint {
  pk_columns: string[];
  fk_columns: string[];
  fk_type: string;
  schema: string;
  table: string;
  pk_keys: number[];
  fk_keys: number[];
  type: "FOREIGN_KEY";
}
export interface FunctionExpression extends ParsedExpression {
  function_name: string;
  schema: string;
  children: AnyParsedExpression[];
  filter: AnyParsedExpression | null;
  order_bys: OrderModifier | null;
  distinct: boolean;
  is_operator: boolean;
  export_state: boolean;
  catalog: string;
  class: "FUNCTION";
}
export interface GenericTypeInfo extends ExtraTypeInfo {
  type: "GENERIC_TYPE_INFO";
}
export interface GeoTypeInfo extends ExtraTypeInfo {
  crs: unknown;
  type: "GEO_TYPE_INFO";
}
export interface HivePartitioningIndex {
  value: string;
  index: number;
}
export interface InFilter extends TableFilter {
  values: DuckDBValue[];
  filter_type: "IN_FILTER";
}
export interface IndexStorageInfo {
  name: string;
  root: number;
  allocator_infos: FixedSizeAllocatorInfo[];
  options: Record<string, DuckDBValue>;
}
export interface IntegerLiteralTypeInfo extends ExtraTypeInfo {
  constant_value: DuckDBValue;
  type: "INTEGER_LITERAL_TYPE_INFO";
}
export interface InvalidTypeInfo extends ExtraTypeInfo {
  type: "INVALID_TYPE_INFO";
}
export interface IsNotNullFilter extends TableFilter {
  filter_type: "IS_NOT_NULL";
}
export interface IsNullFilter extends TableFilter {
  filter_type: "IS_NULL";
}
export interface JoinCondition {
  left: AnyExpression | null;
  right: AnyExpression | null;
  comparison: string;
}
export interface JoinRef extends TableRef {
  left: AnyTableRef | null;
  right: AnyTableRef | null;
  condition: AnyParsedExpression | null;
  join_type: string;
  ref_type: string;
  using_columns: string[];
  delim_flipped: boolean;
  duplicate_eliminated_columns: AnyParsedExpression[];
  /** @since v1.4.0 */
  is_implicit: boolean;
  type: "JOIN";
}
export interface LambdaExpression extends ParsedExpression {
  lhs: AnyParsedExpression | null;
  expr: AnyParsedExpression | null;
  /** @since v1.3.0 */
  syntax_type: string;
  class: "LAMBDA";
}
export interface LambdaRefExpression extends ParsedExpression {
  lambda_idx: number;
  column_name: string;
  class: "LAMBDA_REF";
}
export interface LimitModifier extends ResultModifier {
  limit: AnyParsedExpression | null;
  offset: AnyParsedExpression | null;
  type: "LIMIT_MODIFIER";
}
export interface LimitPercentModifier extends ResultModifier {
  limit: AnyParsedExpression | null;
  offset: AnyParsedExpression | null;
  type: "LIMIT_PERCENT_MODIFIER";
}
export interface ListTypeInfo extends ExtraTypeInfo {
  child_type: DuckDBLogicalType;
  type: "LIST_TYPE_INFO";
}
export interface LoadInfo extends ParseInfo {
  filename: string;
  load_type: string;
  repository: string;
  version: string;
  repo_is_alias: boolean;
  info_type: "LOAD_INFO";
}
export interface LogicalAggregate extends LogicalOperator {
  expressions: AnyExpression[];
  group_index: number;
  aggregate_index: number;
  groupings_index: number;
  groups: AnyExpression[];
  grouping_sets: unknown[];
  grouping_functions: number[][];
  distinct_validity: string;
  type: "LOGICAL_AGGREGATE_AND_GROUP_BY";
}
export interface LogicalAnyJoin extends LogicalOperator {
  join_type: string;
  mark_index: number;
  left_projection_map: number[];
  right_projection_map: number[];
  condition: AnyExpression | null;
  type: "LOGICAL_ANY_JOIN";
}
export interface LogicalCTERef extends LogicalOperator {
  table_index: number;
  cte_index: number;
  chunk_types: DuckDBLogicalType[];
  bound_columns: string[];
  is_recurring: boolean;
  type: "LOGICAL_CTE_REF";
}
export interface LogicalColumnDataGet extends LogicalOperator {
  table_index: number;
  chunk_types: DuckDBLogicalType[];
  collection: unknown | null;
  type: "LOGICAL_CHUNK_GET";
}
export interface LogicalComparisonJoin extends LogicalOperator {
  join_type: string;
  mark_index: number;
  left_projection_map: number[];
  right_projection_map: number[];
  conditions: JoinCondition[];
  mark_types: DuckDBLogicalType[];
  duplicate_eliminated_columns: AnyExpression[];
  delim_flipped: boolean;
  predicate: AnyExpression | null;
  type: "LOGICAL_ASOF_JOIN" | "LOGICAL_COMPARISON_JOIN" | "LOGICAL_DELIM_JOIN";
}
export interface LogicalCopyDatabase extends LogicalOperator {
  info: CopyDatabaseInfo | null;
  type: "LOGICAL_COPY_DATABASE";
}
export interface LogicalCopyToFile extends LogicalOperator {
  type: "LOGICAL_COPY_TO_FILE";
}
export interface LogicalCreate extends LogicalOperator {
  info: AnyCreateInfo | null;
  type: "LOGICAL_CREATE_SEQUENCE" | "LOGICAL_CREATE_VIEW" | "LOGICAL_CREATE_SCHEMA" | "LOGICAL_CREATE_MACRO" | "LOGICAL_CREATE_TYPE";
}
export interface LogicalCreateIndex extends LogicalOperator {
  info: CreateIndexInfo | null;
  unbound_expressions: AnyExpression[];
  alter_table_info: AnyAlterTableInfo | null;
  type: "LOGICAL_CREATE_INDEX";
}
export interface LogicalCreateTable extends LogicalOperator {
  info: AnyCreateInfo | null;
  type: "LOGICAL_CREATE_TABLE";
}
export interface LogicalCrossProduct extends LogicalOperator {
  type: "LOGICAL_CROSS_PRODUCT";
}
export interface LogicalDelete extends LogicalOperator {
  table_info: AnyCreateInfo | null;
  table_index: number;
  return_chunk: boolean;
  expressions: AnyExpression[];
  type: "LOGICAL_DELETE";
}
export interface LogicalDelimGet extends LogicalOperator {
  table_index: number;
  chunk_types: DuckDBLogicalType[];
  type: "LOGICAL_DELIM_GET";
}
export interface LogicalDependency {
  entry: CatalogEntryInfo;
  catalog: string;
}
export interface LogicalDependencyList {
  set: unknown[];
}
export interface LogicalDistinct extends LogicalOperator {
  distinct_type: string;
  distinct_targets: AnyExpression[];
  order_by: BoundOrderModifier | null;
  type: "LOGICAL_DISTINCT";
}
export interface LogicalDummyScan extends LogicalOperator {
  table_index: number;
  type: "LOGICAL_DUMMY_SCAN";
}
export interface LogicalEmptyResult extends LogicalOperator {
  return_types: DuckDBLogicalType[];
  bindings: ColumnBinding[];
  type: "LOGICAL_EMPTY_RESULT";
}
export interface LogicalExplain extends LogicalOperator {
  explain_type: string;
  physical_plan: string;
  logical_plan_unopt: string;
  logical_plan_opt: string;
  type: "LOGICAL_EXPLAIN";
}
export interface LogicalExport extends LogicalOperator {
  copy_info: CopyInfo | null;
  exported_tables: BoundExportData | null;
  type: "LOGICAL_EXPORT";
}
export interface LogicalExpressionGet extends LogicalOperator {
  table_index: number;
  expr_types: DuckDBLogicalType[];
  expressions: AnyExpression[][];
  type: "LOGICAL_EXPRESSION_GET";
}
export interface LogicalExtensionOperator extends LogicalOperator {
  type: "LOGICAL_EXTENSION_OPERATOR";
}
export interface LogicalFilter extends LogicalOperator {
  expressions: AnyExpression[];
  projection_map: number[];
  type: "LOGICAL_FILTER";
}
export interface LogicalGet extends LogicalOperator {
  type: "LOGICAL_GET";
}
export interface LogicalInsert extends LogicalOperator {
  table_info: AnyCreateInfo | null;
  insert_values: AnyExpression[][];
  column_index_map: Array<[number, number]>;
  expected_types: DuckDBLogicalType[];
  table_index: number;
  return_chunk: boolean;
  bound_defaults: AnyExpression[];
  action_type: string;
  expected_set_types: DuckDBLogicalType[];
  on_conflict_filter: number[];
  on_conflict_condition: AnyExpression | null;
  do_update_condition: AnyExpression | null;
  set_columns: number[];
  set_types: DuckDBLogicalType[];
  excluded_table_index: number;
  columns_to_fetch: number[];
  source_columns: number[];
  expressions: AnyExpression[];
  update_is_del_and_insert: boolean;
  type: "LOGICAL_INSERT";
}
export interface LogicalLimit extends LogicalOperator {
  limit_val: BoundLimitNode;
  offset_val: BoundLimitNode;
  type: "LOGICAL_LIMIT";
}
export interface LogicalMaterializedCTE extends LogicalOperator {
  table_index: number;
  column_count: number;
  ctename: string;
  materialize: string;
  type: "LOGICAL_MATERIALIZED_CTE";
}
export interface LogicalMergeInto extends LogicalOperator {
  table_info: AnyCreateInfo | null;
  table_index: number;
  bound_defaults: AnyExpression[];
  row_id_start: number;
  source_marker: number;
  actions: Record<string, BoundMergeIntoAction[]>;
  return_chunk: boolean;
  type: "LOGICAL_MERGE_INTO";
}
export interface LogicalOperator {
  type: string;
  children: AnyLogicalOperator[];
}
export interface LogicalOrder extends LogicalOperator {
  orders: BoundOrderByNode[];
  projections: number[];
  type: "LOGICAL_ORDER_BY";
}
export interface LogicalPivot extends LogicalOperator {
  pivot_index: number;
  bound_pivot: BoundPivotInfo;
  type: "LOGICAL_PIVOT";
}
export interface LogicalPositionalJoin extends LogicalOperator {
  type: "LOGICAL_POSITIONAL_JOIN";
}
export interface LogicalProjection extends LogicalOperator {
  table_index: number;
  expressions: AnyExpression[];
  type: "LOGICAL_PROJECTION";
}
export interface LogicalRecursiveCTE extends LogicalOperator {
  union_all: boolean;
  ctename: string;
  table_index: number;
  column_count: number;
  key_targets: AnyExpression[];
  ref_recurring: boolean;
  type: "LOGICAL_RECURSIVE_CTE";
}
export interface LogicalReset extends LogicalOperator {
  name: string;
  scope: string;
  type: "LOGICAL_RESET";
}
export interface LogicalSample extends LogicalOperator {
  sample_options: SampleOptions | null;
  type: "LOGICAL_SAMPLE";
}
export interface LogicalSet extends LogicalOperator {
  name: string;
  value: DuckDBValue;
  scope: string;
  type: "LOGICAL_SET";
}
export interface LogicalSetOperation extends LogicalOperator {
  table_index: number;
  column_count: number;
  setop_all: boolean;
  allow_out_of_order: boolean;
  type: "LOGICAL_UNION" | "LOGICAL_EXCEPT" | "LOGICAL_INTERSECT";
}
export interface LogicalSimple extends LogicalOperator {
  info: AnyParseInfo | null;
  type: "LOGICAL_ALTER" | "LOGICAL_LOAD" | "LOGICAL_ATTACH" | "LOGICAL_TRANSACTION" | "LOGICAL_DROP" | "LOGICAL_DETACH";
}
export interface LogicalTopN extends LogicalOperator {
  orders: BoundOrderByNode[];
  limit: number;
  offset: number;
  type: "LOGICAL_TOP_N";
}
export interface LogicalTypeModifier {
  value: DuckDBValue;
  label: string;
}
export interface LogicalUnnest extends LogicalOperator {
  unnest_index: number;
  expressions: AnyExpression[];
  type: "LOGICAL_UNNEST";
}
export interface LogicalUpdate extends LogicalOperator {
  table_info: AnyCreateInfo | null;
  table_index: number;
  return_chunk: boolean;
  expressions: AnyExpression[];
  columns: number[];
  bound_defaults: AnyExpression[];
  update_is_del_and_insert: boolean;
  type: "LOGICAL_UPDATE";
}
export interface LogicalVacuum extends LogicalOperator {
  type: "LOGICAL_VACUUM";
}
export interface LogicalWindow extends LogicalOperator {
  window_index: number;
  expressions: AnyExpression[];
  type: "LOGICAL_WINDOW";
}
export interface MacroFunction {
  type: string;
  parameters: AnyParsedExpression[];
  default_parameters: Record<string, AnyParsedExpression>;
  /** @since v1.4.0 */
  types: DuckDBLogicalType[];
}
export interface MetaBlockPointer {
  block_pointer: number;
  offset: number;
}
export interface MultiFileOptions {
  filename: boolean;
  hive_partitioning: boolean;
  auto_detect_hive_partitioning: boolean;
  union_by_name: boolean;
  hive_types_autocast: boolean;
  hive_types_schema: Record<string, DuckDBLogicalType>;
  filename_column: string;
}
export interface MultiFileReaderBindData {
  filename_idx: number;
  hive_partitioning_indexes: HivePartitioningIndex[];
}
export interface NotNullConstraint extends Constraint {
  index: number;
  type: "NOT_NULL";
}
export interface OperatorExpression extends ParsedExpression {
  children: AnyParsedExpression[];
  class: "OPERATOR";
}
export interface OptionalFilter extends TableFilter {
  child_filter: AnyTableFilter | null;
  filter_type: "OPTIONAL_FILTER";
}
export interface OrderByNode {
  type: string;
  null_order: string;
  expression: AnyParsedExpression | null;
}
export interface OrderModifier extends ResultModifier {
  orders: OrderByNode[];
  type: "ORDER_MODIFIER";
}
export interface ParameterExpression extends ParsedExpression {
  identifier: string;
  class: "PARAMETER";
}
export interface ParseInfo {
  info_type: string;
}
export interface ParsedExpression {
  class: string;
  type: string;
  alias: string;
  query_location: number;
}
export interface PivotColumn {
  pivot_expressions: AnyParsedExpression[];
  unpivot_names: string[];
  entries: PivotColumnEntry[];
  pivot_enum: string;
}
export interface PivotColumnEntry {
  values: DuckDBValue[];
  star_expr: AnyParsedExpression | null;
  alias: string;
}
export interface PivotRef extends TableRef {
  source: AnyTableRef | null;
  aggregates: AnyParsedExpression[];
  unpivot_names: string[];
  pivots: PivotColumn[];
  groups: string[];
  column_name_alias: string[];
  include_nulls: boolean;
  type: "PIVOT";
}
export interface PositionalReferenceExpression extends ParsedExpression {
  index: number;
  class: "POSITIONAL_REFERENCE";
}
export interface PragmaInfo extends ParseInfo {
  name: string;
  parameters: AnyParsedExpression[];
  named_parameters: Record<string, AnyParsedExpression>;
  info_type: "PRAGMA_INFO";
}
export interface QualifiedColumnName {
  catalog: string;
  schema: string;
  table: string;
  column: string;
}
export interface QueryNode {
  type: string;
  modifiers: AnyResultModifier[];
  cte_map: CommonTableExpressionMap;
}
export interface RecursiveCTENode extends QueryNode {
  cte_name: string;
  union_all: boolean;
  left: AnyQueryNode | null;
  right: AnyQueryNode | null;
  aliases: string[];
  key_targets: AnyParsedExpression[];
  type: "RECURSIVE_CTE_NODE";
}
export interface RemoveColumnInfo extends AlterTableInfo {
  removed_column: string;
  if_column_exists: boolean;
  cascade: boolean;
  alter_table_type: "REMOVE_COLUMN";
}
export interface RemoveFieldInfo extends AlterTableInfo {
  column_path: string[];
  if_column_exists: boolean;
  cascade: boolean;
  alter_table_type: "REMOVE_FIELD";
}
export interface RenameColumnInfo extends AlterTableInfo {
  old_name: string;
  new_name: string;
  alter_table_type: "RENAME_COLUMN";
}
export interface RenameDatabaseInfo extends AlterDatabaseInfo {
  new_name: string;
  alter_database_type: "RENAME_DATABASE";
}
export interface RenameFieldInfo extends AlterTableInfo {
  column_path: string[];
  new_name: string;
  alter_table_type: "RENAME_FIELD";
}
export interface RenameTableInfo extends AlterTableInfo {
  new_table_name: string;
  alter_table_type: "RENAME_TABLE";
}
export interface RenameViewInfo extends AlterViewInfo {
  new_view_name: string;
  alter_view_type: "RENAME_VIEW";
}
export interface ReservoirSample extends BlockingSample {
  sample_count: number;
  reservoir_chunk: unknown | null;
  type: "RESERVOIR_SAMPLE";
}
export interface ReservoirSamplePercentage extends BlockingSample {
  sample_percentage: number;
  reservoir_sample_size: number;
  type: "RESERVOIR_PERCENTAGE_SAMPLE";
}
export interface ResetTableOptionsInfo extends AlterTableInfo {
  table_options: string[];
  alter_table_type: "RESET_TABLE_OPTIONS";
}
export interface ResultModifier {
  type: string;
}
export interface RowGroupOrderOptions {
  column_idx: StorageIndex;
  order_by: string;
  order_type: string;
  null_order: string;
  column_type: string;
  row_limit: number;
  row_group_offset: number;
  leading_null_group_offset: number;
}
export interface SampleOptions {
  sample_size: DuckDBValue;
  is_percentage: boolean;
  method: string;
  seed: number;
}
export interface ScalarMacroFunction extends MacroFunction {
  expression: AnyParsedExpression | null;
  type: "SCALAR_MACRO";
}
export interface SelectNode extends QueryNode {
  select_list: AnyParsedExpression[];
  from_table: AnyTableRef | null;
  where_clause: AnyParsedExpression | null;
  group_expressions: AnyParsedExpression[];
  group_sets: unknown[];
  aggregate_handling: string;
  having: AnyParsedExpression | null;
  sample: SampleOptions | null;
  qualify: AnyParsedExpression | null;
  type: "SELECT_NODE";
}
export interface SelectStatement {
  node: AnyQueryNode | null;
  named_param_map: Record<string, number>;
}
export interface SerializedCSVReaderOptions {
  ignore_errors: boolean;
  buffer_sample_size: number;
  null_str: string[];
  compression: string;
  allow_quoted_nulls: boolean;
  maximum_line_size: CSVOption<number>;
  normalize_names: boolean;
  force_not_null: boolean[];
  all_varchar: boolean;
  sample_size_chunks: number;
  auto_detect: boolean;
  file_path: string;
  decimal_separator: string;
  null_padding: boolean;
  file_options: MultiFileOptions;
  force_quote: boolean[];
  rejects_table_name: string;
  rejects_limit: number;
  delimiter: CSVOption<string>;
  quote: CSVOption<string>;
  escape: CSVOption<string>;
  header: CSVOption<boolean>;
  num_cols: number;
  new_line: CSVOption<string>;
  skip_rows: CSVOption<number>;
  date_format: Record<string, CSVOption<StrpTimeFormat>>;
  sniffer_user_mismatch_error: string;
  parallel: boolean;
  was_type_manually_set: boolean[];
  rejects_scan_name: CSVOption<string>;
  name_list: string[];
  sql_type_list: DuckDBLogicalType[];
  sql_types_per_column: Record<string, number>;
  columns_set: boolean;
  comment: CSVOption<string>;
  rows_until_header: number;
  encoding: string;
  strict_mode: CSVOption<boolean>;
  multi_byte_delimiter: CSVOption<string>;
  multi_file_reader: boolean;
  buffer_size_option: CSVOption<number>;
}
export interface SerializedReadCSVData {
  files: string[];
  csv_types: DuckDBLogicalType[];
  csv_names: string[];
  return_types: DuckDBLogicalType[];
  return_names: string[];
  filename_col_idx: number;
  options: SerializedCSVReaderOptions;
  reader_bind: MultiFileReaderBindData;
  column_info: ColumnInfo[];
}
export interface SetColumnCommentInfo extends AlterInfo {
  catalog_entry_type: string;
  comment_value: DuckDBValue;
  column_name: string;
  type: "SET_COLUMN_COMMENT";
}
export interface SetCommentInfo extends AlterInfo {
  entry_catalog_type: string;
  comment_value: DuckDBValue;
  type: "SET_COMMENT";
}
export interface SetDefaultInfo extends AlterTableInfo {
  column_name: string;
  expression: AnyParsedExpression | null;
  alter_table_type: "SET_DEFAULT";
}
export interface SetNotNullInfo extends AlterTableInfo {
  column_name: string;
  alter_table_type: "SET_NOT_NULL";
}
export interface SetOperationNode extends QueryNode {
  setop_type: string;
  left: AnyQueryNode | null;
  right: AnyQueryNode | null;
  setop_all: boolean;
  children: AnyQueryNode[];
  type: "SET_OPERATION_NODE";
}
export interface SetPartitionedByInfo extends AlterTableInfo {
  partition_keys: AnyParsedExpression[];
  alter_table_type: "SET_PARTITIONED_BY";
}
export interface SetSortedByInfo extends AlterTableInfo {
  orders: OrderByNode[];
  alter_table_type: "SET_SORTED_BY";
}
export interface SetTableOptionsInfo extends AlterTableInfo {
  table_options: Record<string, AnyParsedExpression>;
  alter_table_type: "SET_TABLE_OPTIONS";
}
export interface ShowRef extends TableRef {
  table_name: string;
  query: AnyQueryNode | null;
  show_type: string;
  catalog_name: string;
  schema_name: string;
  type: "SHOW_REF";
}
export interface StarExpression extends ParsedExpression {
  relation_name: string;
  exclude_list: string[];
  replace_list: Record<string, AnyParsedExpression>;
  columns: boolean;
  expr: AnyParsedExpression | null;
  unpacked: boolean;
  qualified_exclude_list: string[];
  rename_list: Record<string, string>;
  class: "STAR";
}
export interface StorageIndex {
  has_index: boolean;
  index: number;
  field: string;
  type: DuckDBLogicalType;
  index_type: string;
  child_indexes: StorageIndex[];
}
export interface StringTypeInfo extends ExtraTypeInfo {
  collation: string;
  type: "STRING_TYPE_INFO";
}
export interface StrpTimeFormat {
  format_specifier: string;
}
export interface StructFilter extends TableFilter {
  child_idx: number;
  child_name: string;
  child_filter: AnyTableFilter | null;
  filter_type: "STRUCT_EXTRACT";
}
export interface StructTypeInfo extends ExtraTypeInfo {
  child_types: Record<string, DuckDBLogicalType>;
  type: "STRUCT_TYPE_INFO";
}
export interface SubqueryExpression extends ParsedExpression {
  subquery_type: string;
  subquery: SelectStatement | null;
  child: AnyParsedExpression | null;
  comparison_type: string;
  class: "SUBQUERY";
}
export interface SubqueryRef extends TableRef {
  subquery: SelectStatement | null;
  column_name_alias: string[];
  type: "SUBQUERY";
}
export interface TableColumn {
  name: string;
  type: DuckDBLogicalType;
}
export interface TableFilter {
  filter_type: string;
}
export interface TableFilterSet {
  filters: Record<string, AnyTableFilter>;
}
export interface TableFunctionRef extends TableRef {
  function: AnyParsedExpression | null;
  column_name_alias: string[];
  with_ordinality: string;
  type: "TABLE_FUNCTION";
}
export interface TableMacroFunction extends MacroFunction {
  query_node: AnyQueryNode | null;
  type: "TABLE_MACRO";
}
export interface TableRef {
  type: string;
  alias: string;
  sample: SampleOptions | null;
  query_location: number;
}
export interface TemplateTypeInfo extends ExtraTypeInfo {
  name: string;
  type: "TEMPLATE_TYPE_INFO";
}
export interface TransactionInfo extends ParseInfo {
  type: string;
  modifier: string;
  invalidation_policy: string;
  auto_rollback: boolean;
  info_type: "TRANSACTION_INFO";
}
export interface TypeExpression extends ParsedExpression {
  catalog: string;
  schema: string;
  type_name: string;
  children: AnyParsedExpression[];
  class: "TYPE";
}
export interface UnboundTypeInfo extends ExtraTypeInfo {
  type: "UNBOUND_TYPE_INFO";
}
export interface UniqueConstraint extends Constraint {
  is_primary_key: boolean;
  index: number;
  columns: string[];
  type: "UNIQUE";
}
export interface UpdateExtensionsInfo extends ParseInfo {
  extensions_to_update: string[];
  info_type: "UPDATE_EXTENSIONS_INFO";
}
export interface VacuumInfo extends ParseInfo {
  options: VacuumOptions;
  has_table: boolean;
  ref: AnyTableRef | null;
  columns: string[];
  info_type: "VACUUM_INFO";
}
export interface VacuumOptions {
  vacuum: boolean;
  analyze: boolean;
}
export interface WindowExpression extends ParsedExpression {
  function_name: string;
  schema: string;
  catalog: string;
  children: AnyParsedExpression[];
  partitions: AnyParsedExpression[];
  orders: OrderByNode[];
  start: string;
  end: string;
  start_expr: AnyParsedExpression | null;
  end_expr: AnyParsedExpression | null;
  offset_expr: AnyParsedExpression | null;
  default_expr: AnyParsedExpression | null;
  ignore_nulls: boolean;
  filter_expr: AnyParsedExpression | null;
  exclude_clause: string;
  distinct: boolean;
  arg_orders: OrderByNode[];
  class: "WINDOW";
}
export interface interval_t {
  months: number;
  days: number;
  micros: number;
}

export type AnyAlterDatabaseInfo = RenameDatabaseInfo;
export type AnyAlterInfo = AddColumnInfo | AddConstraintInfo | AddFieldInfo | AlterForeignKeyInfo | ChangeColumnTypeInfo | ChangeOwnershipInfo | DropNotNullInfo | RemoveColumnInfo | RemoveFieldInfo | RenameColumnInfo | RenameDatabaseInfo | RenameFieldInfo | RenameTableInfo | RenameViewInfo | ResetTableOptionsInfo | SetColumnCommentInfo | SetCommentInfo | SetDefaultInfo | SetNotNullInfo | SetPartitionedByInfo | SetSortedByInfo | SetTableOptionsInfo;
export type AnyAlterTableInfo = AddColumnInfo | AddConstraintInfo | AddFieldInfo | AlterForeignKeyInfo | ChangeColumnTypeInfo | DropNotNullInfo | RemoveColumnInfo | RemoveFieldInfo | RenameColumnInfo | RenameFieldInfo | RenameTableInfo | ResetTableOptionsInfo | SetDefaultInfo | SetNotNullInfo | SetPartitionedByInfo | SetSortedByInfo | SetTableOptionsInfo;
export type AnyAlterViewInfo = RenameViewInfo;
export type AnyBlockingSample = ReservoirSample | ReservoirSamplePercentage;
export type AnyConstraint = CheckConstraint | ForeignKeyConstraint | NotNullConstraint | UniqueConstraint;
export type AnyCreateInfo = CreateIndexInfo | CreateMacroInfo | CreateSchemaInfo | CreateSequenceInfo | CreateTableInfo | CreateTypeInfo | CreateViewInfo;
export type AnyExpression = BoundAggregateExpression | BoundBetweenExpression | BoundCaseExpression | BoundCastExpression | BoundColumnRefExpression | BoundComparisonExpression | BoundConjunctionExpression | BoundConstantExpression | BoundDefaultExpression | BoundFunctionExpression | BoundLambdaExpression | BoundLambdaRefExpression | BoundOperatorExpression | BoundParameterExpression | BoundReferenceExpression | BoundUnnestExpression | BoundWindowExpression;
export type AnyExtraDropInfo = ExtraDropSecretInfo;
export type AnyExtraTypeInfo = AggregateStateTypeInfo | AnyTypeInfo | ArrayTypeInfo | DecimalTypeInfo | EnumTypeInfo | GenericTypeInfo | GeoTypeInfo | IntegerLiteralTypeInfo | InvalidTypeInfo | ListTypeInfo | StringTypeInfo | StructTypeInfo | TemplateTypeInfo | UnboundTypeInfo;
export type AnyLogicalOperator = LogicalAggregate | LogicalAnyJoin | LogicalCTERef | LogicalColumnDataGet | LogicalComparisonJoin | LogicalCopyDatabase | LogicalCopyToFile | LogicalCreate | LogicalCreateIndex | LogicalCreateTable | LogicalCrossProduct | LogicalDelete | LogicalDelimGet | LogicalDistinct | LogicalDummyScan | LogicalEmptyResult | LogicalExplain | LogicalExport | LogicalExpressionGet | LogicalExtensionOperator | LogicalFilter | LogicalGet | LogicalInsert | LogicalLimit | LogicalMaterializedCTE | LogicalMergeInto | LogicalOrder | LogicalPivot | LogicalPositionalJoin | LogicalProjection | LogicalRecursiveCTE | LogicalReset | LogicalSample | LogicalSet | LogicalSetOperation | LogicalSimple | LogicalTopN | LogicalUnnest | LogicalUpdate | LogicalVacuum | LogicalWindow;
export type AnyMacroFunction = ScalarMacroFunction | TableMacroFunction;
export type AnyParseInfo = AddColumnInfo | AddConstraintInfo | AddFieldInfo | AlterForeignKeyInfo | AttachInfo | BoundExportData | ChangeColumnTypeInfo | ChangeOwnershipInfo | CopyDatabaseInfo | CopyInfo | DetachInfo | DropInfo | DropNotNullInfo | LoadInfo | PragmaInfo | RemoveColumnInfo | RemoveFieldInfo | RenameColumnInfo | RenameDatabaseInfo | RenameFieldInfo | RenameTableInfo | RenameViewInfo | ResetTableOptionsInfo | SetColumnCommentInfo | SetCommentInfo | SetDefaultInfo | SetNotNullInfo | SetPartitionedByInfo | SetSortedByInfo | SetTableOptionsInfo | TransactionInfo | UpdateExtensionsInfo | VacuumInfo;
export type AnyParsedExpression = BetweenExpression | CaseExpression | CastExpression | CollateExpression | ColumnRefExpression | ComparisonExpression | ConjunctionExpression | ConstantExpression | DefaultExpression | FunctionExpression | LambdaExpression | LambdaRefExpression | OperatorExpression | ParameterExpression | PositionalReferenceExpression | StarExpression | SubqueryExpression | TypeExpression | WindowExpression;
export type AnyQueryNode = CTENode | RecursiveCTENode | SelectNode | SetOperationNode;
export type AnyResultModifier = DistinctModifier | LimitModifier | LimitPercentModifier | OrderModifier;
export type AnyTableFilter = ConjunctionAndFilter | ConjunctionOrFilter | ConstantFilter | DynamicFilter | ExpressionFilter | InFilter | IsNotNullFilter | IsNullFilter | OptionalFilter | StructFilter;
export type AnyTableRef = BaseTableRef | ColumnDataRef | EmptyTableRef | ExpressionListRef | JoinRef | PivotRef | ShowRef | SubqueryRef | TableFunctionRef;
